---
jmx_exporter_service_enabled: true
jmx_exporter_service_state: started

jmx_exporter_port: 9119

jmx_rmi: true

jmx_exporter_config_template_path: "{{ playbook_dir }}/templates/jmx_exporter/config/jmxexporter.yml"
